import {getGamePlan} from './game-core/index.js';
import {renderRivalRoster,revealActivePlayer} from './rival-portraits.js';
import {mascotForSeat,escapeHtml as esc} from './table-view.js';
import {cardAsset} from './card-art.js';

let pokerSpanishView=false;
const ui={key:'',cards:new Set(),table:new Set(),path:[]};
const symbols={oros:'●',copas:'♜',espadas:'⚔',bastos:'♣',picas:'♠',corazones:'♥',diamantes:'♦',treboles:'♣'};
const characters=['Berenjena','Melocotón','Plátano','Japón','Aguacate','Cerdito','Seta','Gota','Caca','Huevos'];
const actionButton=(label,action,extra='')=>`<button data-action="${action}" ${extra}>${esc(label)}</button>`;
function face(card){if(!card)return '<span class="catalog-card-back" aria-label="Carta oculta">✦</span>';
 const pokerSpanish=['oros','copas','espadas','bastos'].includes(card.suit)&&['A','J','Q','K'].includes(card.rank);
 if(card.suit==='joker'||pokerSpanish||card.pokerSpanish||pokerSpanishView)return `<span class="catalog-drawn-face"><b>${esc(card.suit==='joker'?'★':card.rank)}</b><strong>${esc(card.suit==='joker'?'★':symbols[card.suit])}</strong><small>${esc(card.suit==='joker'?'COMODÍN':card.suit)}</small></span>`;
 return `<img src="${cardAsset(card)}" alt="${esc(card.rank)} de ${esc(card.suit)}" draggable="false">`;
}
function cardHtml(card,{action,chosen=false,disabled=false,label}={}){const title=label||`${card.rank} de ${card.suit}`,tag=action?'button':'div';return `<${tag} class="catalog-card ${chosen?'is-selected':''} ${disabled?'is-muted':''}" ${action?`data-action="${action}" data-card-id="${esc(card.id)}" aria-pressed="${chosen}" ${disabled?'disabled':''}`:''} aria-label="${esc(title)}">${face(card)}</${tag}>`;}
function tile(t){return `<span class="domino-half" aria-label="${t.left}">${pips(t.left)}</span><span class="domino-half" aria-label="${t.right}">${pips(t.right)}</span>`;}
function pips(n){const positions={0:[],1:[4],2:[0,8],3:[0,4,8],4:[0,2,6,8],5:[0,2,4,6,8],6:[0,2,3,5,6,8]}[n];return Array.from({length:9},(_,i)=>`<i class="${positions.includes(i)?'pip':''}"></i>`).join('');}
function publicCards(cards){return `<div class="catalog-public-cards">${cards.map(c=>c?cardHtml(c):'<div class="catalog-card">'+face(null)+'</div>').join('')}</div>`;}
function board(view,name,interactive=true){
 switch(view.boardKind){
 case 'tricks':return `<div class="catalog-table-meta"><span>Triunfo <b>${esc(view.trump==='none'?'Sin triunfo':view.trump)}</b></span>${view.stockCount?`<span>Mazo <b>${view.stockCount}</b></span>`:''}${view.pinta&&view.stockCount?`<span>Pinta <b>${esc(view.pinta.rank)} de ${esc(view.pinta.suit)}</b></span>`:''}${view.multiplier>1?`<span>×${view.multiplier}</span>`:''}${view.pot?`<span>Plato <b>${view.pot}</b></span>`:''}</div><div class="catalog-trick">${view.trick.map(t=>`<div><small>${esc(name(t.player))}</small>${cardHtml(t.card)}</div>`).join('')||'<p class="catalog-empty">La mesa está lista</p>'}</div><div class="catalog-scoreline">${view.players.map(p=>`<span>${esc(name(p))}<b>${view.predictions[p]!==undefined?`${view.tricks[p]} / ${view.predictions[p]} bazas`:view.points[p]+' tantos'}</b></span>`).join('')}</div>`;
 case 'domino':return `<div class="domino-chain">${view.chain.map(t=>`<div class="domino-tile ${t.left===t.right?'is-double':''}" aria-label="${t.left} y ${t.right}">${tile(t)}</div>`).join('')||'<p class="catalog-empty">Coloca la primera ficha</p>'}</div>`;
 case 'checkers':{const moves=view.moves.filter(m=>ui.path.every((x,i)=>m.path[i]===x)),destinations=new Set(moves.map(m=>m.path[ui.path.length]));return `<div class="checkers-board" aria-label="Tablero de damas">${view.board.map((piece,i)=>`<button class="checker-square ${(Math.floor(i/8)+i%8)%2===0?'light':'dark'} ${destinations.has(i)?'legal-square':''} ${ui.path.includes(i)?'selected-square':''}" data-action="catalog-checker" data-square="${i}" ${!interactive||!destinations.has(i)&&!ui.path.includes(i)?'disabled':''} aria-label="Casilla ${i+1}${piece?`, ${piece>0?'blanca':'negra'}${Math.abs(piece)===2?' coronada':''}`:''}">${piece?`<span class="checker-piece ${piece>0?'white':'black'}">${Math.abs(piece)===2?'♛':''}</span>`:''}</button>`).join('')}</div>${ui.path.length?actionButton('Cancelar selección','catalog-clear'):''}`;}
 case 'oca':return `<div class="goose-board" aria-label="Tablero de la oca">${Array.from({length:63},(_,i)=>{const n=i+1,kind=[5,9,14,18,23,27,32,36,41,45,50,54,59].includes(n)?'oca':({6:'puente',12:'puente',19:'posada',26:'dados',31:'pozo',42:'laberinto',52:'prisión',53:'dados',58:'calavera',63:'meta'})[n];return `<div class="goose-cell ${kind?'special':''}" title="${n}${kind?' · '+kind:''}"><b>${n}</b><small>${esc(kind||'')}</small><div>${view.players.filter(p=>view.positions[p]===n).map(p=>`<i class="goose-pawn seat-${view.players.indexOf(p)}" title="${esc(name(p))}">${view.players.indexOf(p)+1}</i>`).join('')}</div></div>`;}).join('')}</div>`;
 case 'capture':return `<div class="catalog-table-meta"><span>Mazo <b>${view.stockCount}</b></span></div><div class="capture-cards">${view.table.map(c=>cardHtml(c,{action:interactive?'catalog-table-card':undefined,chosen:ui.table.has(c.id)})).join('')||'<p class="catalog-empty">Mesa limpia</p>'}</div>`;
 case 'bluff':return `<div class="catalog-bluff-pile"><span class="catalog-card-back">✦</span><strong>${view.pileCount} cartas</strong>${view.declaration?`<p>${esc(name(view.declaration.player))}: ${view.declaration.count} de valor ${esc(view.declaration.rank||'—')}</p>`:''}</div>${view.reveal?`<p>${view.reveal.truth?'Decía la verdad':'Era mentira'}</p>${publicCards(view.reveal.cards)}`:''}`;
 case 'burro':return `<div class="catalog-empty"><strong>${view.discardCount/2} parejas fuera</strong><p>${view.hiddenSource?`Robas de ${esc(name(view.hiddenSource))}`:''}</p></div>`;
 case 'melds':return `<div class="catalog-table-meta"><strong>${esc(view.contract)}</strong><span>Mazo ${view.stockCount}</span></div>${view.discard?`<div class="catalog-discard"><small>Descarte</small>${cardHtml(view.discard)}</div>`:''}<div class="catalog-melds">${view.players.filter(p=>view.exposed[p]?.length).map(p=>`<section><small>${esc(name(p))}</small>${view.exposed[p].map(g=>publicCards(g.cards)).join('')}</section>`).join('')}</div>`;
 case 'poker':return `<div class="catalog-table-meta"><span>Bote <b>${view.pot}</b></span><span>${esc(view.phase==='result'?'Recuento':view.phase)}</span></div>${publicCards(view.board)}<div class="catalog-public-hands">${view.players.map(p=>`<section><small>${esc(name(p))} · ${view.chips[p]} fichas${view.folded[p]?' · fuera':''}</small>${view.publicHands[p]?.length?publicCards(view.publicHands[p]):''}</section>`).join('')}</div>${view.payouts.map(pay=>`<p>${pay.pot} fichas → ${pay.winners.map(p=>esc(name(p))).join(', ')}</p>`).join('')}`;
 case 'bank':return `<div class="catalog-table-meta"><span>Banca <b>${esc(name(view.bank))}</b></span></div><div class="catalog-public-hands">${view.players.map(p=>`<section><small>${esc(name(p))}${view.bets[p]?` · apuesta ${view.bets[p]}`:''}</small>${publicCards(view.publicHands[p])}</section>`).join('')}</div>`;
 default:return '';
 }
}
export function renderCatalogGame(app,view,playerId,name,error=''){
 pokerSpanishView=view.id==='remigio';
 const plan=getGamePlan(view.id),key=`${view.id}:${view.handNumber}:${view.turnPlayer}:${view.phase}`;if(ui.key!==key){ui.key=key;ui.cards.clear();ui.table.clear();ui.path=[];}
 const zoom=app.querySelector('.catalog-zoom')?.open,zoomScroll=app.querySelector('.catalog-zoom-content')?.scrollTop||0;
 const menu=app.querySelector('.game-menu')?.open,menuScroll=app.querySelector('.game-menu-content')?.scrollTop||0,boardScroll=app.querySelector('.catalog-surface')?.scrollTop||0,handScroll=app.querySelector('.catalog-hand')?.scrollLeft||0;
 const own=view.players.indexOf(playerId),ordered=Array.from({length:view.players.length},(_,i)=>view.players[(own+i)%view.players.length]);
 const players=ordered.map(id=>{const seat=view.players.indexOf(id),character=mascotForSeat(view.players,seat);return {id,name:name(id),character,mascot:characters[character],count:view.handSizes[id],unit:view.unit||'cartas',active:!view.finished&&view.turnPlayer===id,isSelf:id===playerId,teamLabel:view.teamLabels?.[id]||''};});
 const isTurn=view.turnPlayer===playerId&&!view.finished,selectable=isTurn&&view.selectable,valid=new Set(view.validCards||[]);
 const ranks=plan.material.includes('french')||plan.material.includes('poker')?['A','2','3','4','5','6','7','8','9','10','J','Q','K']:['1','2','3','4','5','6','7','8','9','10','11','12'];
 const suits=Object.keys(symbols).concat('joker');
 const myHand=view.myHand.slice().sort((a,b)=>suits.indexOf(a.suit)-suits.indexOf(b.suit)||ranks.indexOf(a.rank)-ranks.indexOf(b.rank));
 const result=view.finished?(view.loser?`${name(view.loser)} pierde`:view.winner?`${name(view.winner)} gana`:'Tablas'):view.phase==='result'?(view.id==='burro'?`${name(view.loser)}: ${'BURRO'.slice(0,view.scores[view.loser])}`:view.boardKind==='bank'?'Banca resuelta':view.handWinner?`${name(view.handWinner)} gana la mano`:'Mano terminada'):'';
 const controls=view.options.map((option,index)=>{const amount=option.action.amountInput;return `${amount?`<label class="catalog-amount">Hasta <input type="number" id="catalog-amount-${index}" min="${amount.min}" max="${amount.max}" value="${amount.value}" step="1"></label>`:''}${actionButton(option.label,'catalog-choice',`data-index="${index}"`)}`;}).join('');
 app.innerHTML=`<section class="catalog-screen game-page" data-game="${view.id}"><header class="play-header"><div><h1><span>ELTETO</span> ${esc(plan.label)}</h1><p>MANO ${view.handNumber}${view.session?' · '+esc(view.session):''}</p></div><button data-action="catalog-zoom" aria-label="Ampliar mesa">Mesa ↗</button><button class="game-menu-button" data-action="open-game-menu" aria-label="Marcador, reglas y opciones de partida">···</button></header><section class="players-panel" aria-label="Jugadores y turno">${renderRivalRoster(players,esc)}</section><section class="catalog-surface" aria-label="Mesa de ${esc(plan.label)}">${result?`<p class="catalog-result" role="status">${esc(result)}</p>`:''}${board(view,name)}</section><section class="catalog-dock" aria-label="Tu mano y acciones"><p class="catalog-instruction" aria-live="polite">${esc(view.instruction||'')}${error?`<span role="alert">${esc(error)}</span>`:''}</p>${view.boardKind==='oca'?`<div class="catalog-die" aria-label="Dado: ${view.roll||'sin tirar'}">${view.roll?['','⚀','⚁','⚂','⚃','⚄','⚅'][view.roll]:'⚀'}</div>`:''}<div class="catalog-hand" aria-label="Tus cartas o fichas">${view.myTiles?view.myTiles.map(t=>`<div class="domino-tile" aria-label="${t.left} y ${t.right}">${tile(t)}</div>`).join(''):myHand.map(c=>cardHtml(c,{action:'catalog-select-card',chosen:ui.cards.has(c.id),disabled:!selectable&&!valid.has(c.id)})).join('')}</div>${view.rankOptions?.length&&isTurn&&view.phase==='play'?`<label class="catalog-rank">Declaro <select id="catalog-rank">${view.rankOptions.map(rank=>`<option value="${rank}">${rank}</option>`).join('')}</select></label>`:''}<div class="catalog-options">${controls}</div></section><dialog class="game-menu" aria-label="Opciones de partida"><header><h2>Tu partida</h2><button data-action="close-game-menu">Volver</button></header><div class="game-menu-content"><p>${esc(plan.label)} · Mano ${view.handNumber}</p><ul class="scoreboard">${view.players.map(p=>`<li class="${p===playerId?'your-score':''}"><span>${esc(name(p))}${p===playerId?' · tú':''}</span><strong>${view.id==='burro'?('BURRO'.slice(0,view.scores[p])||'—'):Number(view.scores[p]).toLocaleString('es-ES',{maximumFractionDigits:2})}</strong></li>`).join('')}</ul><details><summary>Cómo jugar</summary><p>${esc(plan.summary)}</p><p>${esc(plan.implementationNotes)}</p><a href="./reglas_juegos/lectura/${view.id}.html">Ver reglas</a></details><details><summary>Historial de la partida</summary><ol>${view.log.slice().reverse().map(line=>`<li>${esc(view.players.reduce((text,id)=>text.split(id).join(name(id)),line))}</li>`).join('')}</ol></details><button data-action="leave-room" class="leave-game">Salir</button></div></dialog><dialog class="catalog-zoom"><header><h2>${esc(plan.label)}</h2><button data-action="catalog-close-zoom">Volver</button></header><div class="catalog-zoom-content">${board(view,name,false)}</div></dialog></section>`;
 app.querySelector('.catalog-surface').scrollTop=boardScroll;app.querySelector('.catalog-hand').scrollLeft=handScroll;if(menu){app.querySelector('.game-menu').showModal();app.querySelector('.game-menu-content').scrollTop=menuScroll;}if(zoom){app.querySelector('.catalog-zoom').showModal();app.querySelector('.catalog-zoom-content').scrollTop=zoomScroll;}revealActivePlayer(app);
}
export function handleCatalogAction(app,button,view,send,render){
 const action=button.dataset.action;if(!action.startsWith('catalog-'))return false;
 const reset=()=>{ui.cards.clear();ui.table.clear();ui.path=[];};
 if(action==='catalog-zoom'){app.querySelector('.catalog-zoom').showModal();return true;}
 if(action==='catalog-close-zoom'){app.querySelector('.catalog-zoom').close();return true;}
 if(action==='catalog-clear'){reset();render();return true;}
 if(action==='catalog-checker'){const i=Number(button.dataset.square);if(ui.path.includes(i))ui.path=[];else ui.path.push(i);const exact=view.moves.find(m=>m.path.join(',')===ui.path.join(','));if(exact){send({type:'move',path:[...ui.path]});reset();}else render();return true;}
 if(action==='catalog-select-card'||action==='catalog-table-card'){const id=button.dataset.cardId;if(action==='catalog-select-card'&&view.validCards?.includes(id)){send({type:'play',card:id});return true;}const set=action==='catalog-table-card'?ui.table:ui.cards;if(set.has(id))set.delete(id);else{if(action==='catalog-select-card'&&!view.options.some(o=>o.action.selection))set.clear();set.add(id);}render();return true;}
 if(action==='catalog-choice'){const option=view.options[Number(button.dataset.index)];if(!option)return true;const a={...option.action};if(a.selection){a.cards=[...ui.cards];delete a.selection;}if(a.singleCard){if(ui.cards.size!==1)throw new Error('Selecciona una sola carta de tu mano.');a.card=[...ui.cards][0];delete a.singleCard;}if(a.tableSelection){a.table=[...ui.table];delete a.tableSelection;}if(a.rankInput){a.rank=app.querySelector('#catalog-rank').value;delete a.rankInput;}if(a.amountInput){a.amount=Number(app.querySelector(`#catalog-amount-${button.dataset.index}`).value);delete a.amountInput;}send(a);reset();return true;}
 return true;
}
