import {SPANISH_RANKS,PhysicalCard} from '../deck';
import {State,Action,base,check,choices,deck,deal,finish,finishHand,integer,makeEngine,mapPlayers,next,note,publicView,requireTurn,selected,take} from './shared';

function pairs(s:State,p:string){const groups:Record<string,PhysicalCard[]>={};for(const c of s.hands[p])(groups[c.rank]??=[]).push(c);for(const cards of Object.values(groups))while(cards.length>=2){const two=cards.splice(0,2);two.forEach(c=>take(s,p,c.id));s.discard.push(...two);}}
function burroDeal(s:State){s.stock=deck(s).filter(c=>!(c.suit==='bastos'&&c.rank==='11'));s.discard=[];s.hands=mapPlayers(s.players,()=>[]);s.turn=(s.handNumber-1)%s.players.length;while(s.stock.length)for(const p of s.players)if(s.stock.length)s.hands[p].push(s.stock.pop()!);s.players.forEach(p=>pairs(s,p));s.owner=s.turn;burroPhase(s);}
function neighbor(s:State,seat:number,direction:number){for(let i=1;i<=s.players.length;i++){const n=(seat+direction*i+s.players.length*2)%s.players.length;if(s.hands[s.players[n]].length)return n;}return seat;}
function burroEnd(s:State){const alive=s.players.filter(p=>s.hands[p].length);if(alive.length>1)return false;const loser=alive[0];s.scores[loser]++;s.loser=loser;finishHand(s,loser);note(s,`${loser}: ${'BURRO'.slice(0,s.scores[loser])}.`);if(s.scores[loser]>=5){finish(s);s.loser=loser;}return true;}
function burroPhase(s:State){if(burroEnd(s))return;if(!s.hands[s.players[s.owner]].length)s.owner=neighbor(s,s.owner,1);s.source=s.owner;s.turn=neighbor(s,s.owner,1);s.phase='take-left';}
export const burroEngine=makeEngine('burro',(p,seed)=>{const s=base('burro',p,seed);burroDeal(s);return s;},(s,p,a)=>{
 requireTurn(s,p);if(s.phase==='result'){check(a.type==='next-hand');s.handNumber++;burroDeal(s);return;}
 check(a.type==='draw-hidden');const source=s.players[s.source],i=integer(a.index,0,s.hands[source].length-1);s.hands[p].push(s.hands[source].splice(i,1)[0]);pairs(s,p);note(s,`${p} roba una carta y descarta sus parejas.`);if(burroEnd(s))return;
 if(s.phase==='take-left'&&s.hands[s.players[s.owner]].length){s.turn=s.owner;s.source=neighbor(s,s.owner,-1);s.phase='take-right';}
 else{s.owner=neighbor(s,s.owner,1);burroPhase(s);}
},(s,p)=>publicView(s,p,{boardKind:'burro',loser:s.loser,discardCount:s.discard.length,hiddenSource:s.players[s.source],hiddenCount:s.phase==='result'?0:s.hands[s.players[s.source]].length,instruction:s.phase==='result'?'Las parejas se retiran automáticamente.':'Escoge una carta boca abajo. Las parejas se retiran solas.',options:s.players[s.turn]===p&&!s.finished?(s.phase==='result'?choices(['Siguiente mano',{type:'next-hand'}]):Array.from({length:s.hands[s.players[s.source]].length},(_,index)=>({label:`Carta ${index+1}`,action:{type:'draw-hidden',index}}))) :[]}));

function bluffAdvance(s:State){const alive=s.players.filter(p=>s.hands[p].length);if(alive.length<=1){s.loser=alive[0];finish(s);return;}s.turn=s.players.indexOf(s.last.player);next(s,p=>s.hands[p].length>0);s.phase='play';}
export const mentirosoEngine=makeEngine('mentiroso',(p,seed)=>{const s=base('mentiroso',p,seed);s.stock=deck(s);while(s.stock.length)for(const id of p)if(s.stock.length)s.hands[id].push(s.stock.pop()!);s.pile=[];s.declared=null;s.lastSpeech=null;return s;},(s,p,a)=>{
 requireTurn(s,p);
 if(s.phase==='respond'){
  check(a.type==='challenge'||a.type==='trust');
  if(a.type==='challenge'){s.lastSpeech={sequence:(s.lastSpeech?.sequence??0)+1,player:p,kind:'challenge'};const truth=s.last.cards.every((c:PhysicalCard)=>c.rank==='1'||c.rank===s.declared),loser=truth?p:s.last.player;s.hands[loser].push(...s.pile);s.pile=[];s.reveal={player:s.last.player,cards:s.last.cards,truth};s.declared=null;s.turn=s.players.indexOf(loser);s.phase='play';note(s,truth?`${p} recoge el montón: decía la verdad.`:`${loser} recoge el montón: era mentira.`);const alive=s.players.filter(id=>s.hands[id].length);if(alive.length<=1){s.loser=alive[0];finish(s);}return;}
  s.lastSpeech={sequence:(s.lastSpeech?.sequence??0)+1,player:p,kind:'pass'};note(s,`${p}: paso, me lo creo.`);s.responses--;if(s.responses===0)bluffAdvance(s);else next(s,id=>s.hands[id].length>0);return;
 }
 check(a.type==='play-facedown');const cards=selected(s,p,a.cards);check(cards.length>0);check(SPANISH_RANKS.includes(a.rank)&&a.rank!=='1','Elige un valor del 2 al rey.');check(!s.declared||a.rank===s.declared,'Mantén el valor declarado.');s.lastSpeech={sequence:(s.lastSpeech?.sequence??0)+1,player:p,kind:'declare',count:cards.length,rank:a.rank};s.declared=a.rank;s.last={player:p,cards};s.pile.push(...cards.map(c=>take(s,p,c.id)));s.reveal=null;s.responses=s.players.filter(id=>id!==p&&s.hands[id].length>0).length;s.phase='respond';note(s,`${p} declara ${cards.length} carta(s) de valor ${a.rank}.`);next(s,id=>s.hands[id].length>0);
},(s,p)=>publicView(s,p,{boardKind:'bluff',lastSpeech:s.lastSpeech,pileCount:s.pile.length,declaration:s.last?{player:s.last.player,count:s.last.cards.length,rank:s.declared}:null,reveal:s.reveal,loser:s.loser,selectable:s.phase==='play'&&s.players[s.turn]===p,rankOptions:s.declared?[s.declared]:SPANISH_RANKS.filter(r=>r!=='1'),instruction:s.phase==='respond'?'¿Te lo crees?':'Selecciona cartas y declara su valor.',options:s.finished||s.players[s.turn]!==p?[]:s.phase==='respond'?choices(['Me lo creo',{type:'trust'}],['Mentiroso',{type:'challenge'}]):choices(['Jugar boca abajo',{type:'play-facedown',selection:true,rankInput:true}])}));

const halfValue=(c:PhysicalCard)=>Number(c.rank)>=10?1:Number(c.rank)*2;
const total=(cards:PhysicalCard[])=>cards.reduce((n,c)=>n+halfValue(c),0);
function bankDeal(s:State){if(s.chips[s.players[s.bank]]<2*(s.players.filter(p=>s.chips[p]>0).length-1))s.bank=s.players.indexOf(s.players.reduce((a,b)=>s.chips[a]>=s.chips[b]?a:b));s.hands=mapPlayers(s.players,()=>[]);s.stock=deck(s);s.bets=mapPlayers(s.players,()=>0);s.hidden=mapPlayers(s.players,()=>0);s.done=mapPlayers(s.players,p=>s.chips[p]<=0);deal(s,1);s.phase='bet';s.turn=s.bank;next(s,p=>!s.done[p]);if(s.turn===s.bank)finish(s,s.players[s.bank]);}
function bankNext(s:State){s.done[s.players[s.turn]]=true;next(s,p=>!s.done[p]||p===s.players[s.bank]);s.phase=s.turn===s.bank?'bank':'bet';if(s.turn===s.bank){s.hidden[s.players[s.bank]]=-1;if(s.players.every((p,i)=>i===s.bank||total(s.hands[p])>15||!s.bets[p]))settleBank(s);}}
function settleBank(s:State){const bank=s.players[s.bank],bankValue=total(s.hands[bank]);let successor:string|undefined;
 for(const p of s.players){if(p===bank||!s.bets[p])continue;const score=total(s.hands[p]),wins=score<=15&&(bankValue>15||score>bankValue),amount=s.bets[p]*(wins&&score===15?2:1);s.chips[p]+=wins?amount:-amount;s.chips[bank]+=wins?-amount:amount;if(wins&&score===15&&!successor)successor=p;}
 s.scores={...s.chips};s.nextBank=successor?s.players.indexOf(successor):s.bank;if(s.chips[s.players[s.nextBank]]<=0)s.nextBank=s.players.indexOf(s.players.reduce((a,b)=>s.chips[a]>=s.chips[b]?a:b));finishHand(s,bank);note(s,'Banca resuelta. Se muestran todas las cartas.');if(s.handNumber>=15||s.players.filter(p=>s.chips[p]>0).length<=1)finish(s,s.players.reduce((a,b)=>s.chips[a]>=s.chips[b]?a:b));
}
export const sieteEngine=makeEngine('siete_y_medio',(p,seed)=>{const s=base('siete_y_medio',p,seed);s.chips=mapPlayers(p,()=>100);s.scores={...s.chips};s.bank=0;bankDeal(s);return s;},(s,p,a)=>{
 requireTurn(s,p);if(s.phase==='result'){check(a.type==='next-hand');s.handNumber++;s.bank=s.nextBank;bankDeal(s);return;}
 if(s.phase==='bet'){check(a.type==='bet');const limit=Math.min(s.chips[p],10,Math.floor(s.chips[s.players[s.bank]]/(2*(s.players.length-1))));check(limit>=1,'La banca no puede cubrir esta apuesta.');s.bets[p]=integer(a.amount,1,limit);s.phase='hit';return;}
 check(a.type==='hit'||a.type==='stand');if(a.type==='stand'){if(s.turn===s.bank)settleBank(s);else bankNext(s);return;}
 check(s.stock.length,'Mazo agotado: debes plantarte.');s.hands[p].push(s.stock.pop()!);if(a.hidden&&s.turn!==s.bank)s.hidden[p]=s.hands[p].length-1;
 if(total(s.hands[p])>15){s.hidden[p]=-1;if(s.turn===s.bank)settleBank(s);else bankNext(s);}
},(s,p)=>{const show=s.phase==='result'||s.finished;let options:any[]=[];if(s.players[s.turn]===p&&!s.finished){if(s.phase==='result')options=choices(['Siguiente mano',{type:'next-hand'}]);else if(s.phase==='bet'){const limit=Math.min(s.chips[p],10,Math.floor(s.chips[s.players[s.bank]]/(2*(s.players.length-1))));options=Array.from({length:limit},(_,i)=>({label:`${i+1} fichas`,action:{type:'bet',amount:i+1}}));}else options=[...choices(['Plantarse',{type:'stand'}]),...(s.stock.length?choices(['Pedir boca arriba',{type:'hit',hidden:false}],...(s.turn===s.bank?[]:[['Pedir oculta',{type:'hit',hidden:true}] as [string,Action]])):[])];}return publicView(s,p,{boardKind:'bank',bank:s.players[s.bank],bets:s.bets,chips:s.chips,total:total(s.hands[p])/2,publicHands:mapPlayers(s.players,id=>s.hands[id].map((c,i)=>show||id===p||i!==s.hidden[id]?c:null)),instruction:s.phase==='bet'?'Apuesta fichas de la partida.':`Tu suma: ${total(s.hands[p])/2}. Objetivo: 7½.`,session:'15 manos · 100 fichas iniciales · sin dinero',options});});

const value=(c:PhysicalCard)=>Number(c.rank)>7?Number(c.rank)-2:Number(c.rank);
export function captures15(cards:PhysicalCard[],target:number):string[][]{const out:string[][]=[];function walk(i:number,left:number,ids:string[]){if(left===0){out.push(ids);return;}if(left<0)return;for(let j=i;j<cards.length;j++)walk(j+1,left-value(cards[j]),[...ids,cards[j].id]);}walk(0,target,[]);return out;}
function escobaDeal(s:State){s.lastPlay=null;s.stock=deck(s);s.hands=mapPlayers(s.players,()=>[]);s.captured=mapPlayers(s.players,()=>[]);s.sweeps=mapPlayers(s.players,()=>0);s.turn=(s.handNumber-1)%s.players.length;s.dealer=(s.turn+s.players.length-1)%s.players.length;deal(s,3);s.table=s.stock.splice(-4);s.lastCapture=s.players[s.dealer];s.phase='play';const sum=s.table.reduce((n:number,c:PhysicalCard)=>n+value(c),0);if(sum===15||sum===30){s.sweeps[s.lastCapture]=sum/15;s.captured[s.lastCapture].push(...s.table);s.table=[];}}
function escobaScore(s:State){s.captured[s.lastCapture].push(...s.table);s.table=[];const teams=s.players.length>=4?[s.players.filter((_:string,i:number)=>i%2===0),s.players.filter((_:string,i:number)=>i%2===1)]:s.players.map(p=>[p]);const cards=teams.map(ps=>ps.flatMap(p=>s.captured[p]));const counts=cards.map(cs=>[cs.length,cs.filter((c:PhysicalCard)=>c.suit==='oros').length,cs.filter((c:PhysicalCard)=>c.rank==='7').length]);const gains=teams.map(ps=>ps.reduce((n,p)=>n+s.sweeps[p],0));if(teams.length===2)teams.forEach((_,i)=>{if(cards[1-i].length<10)gains[i]+=2;});
 teams.forEach((_,i)=>{if(cards[i].some((c:PhysicalCard)=>c.suit==='oros'&&c.rank==='7'))gains[i]++;for(const category of [0,1,2]){const max=Math.max(...counts.map(c=>c[category]));if(counts[i][category]===max&&counts.filter(c=>c[category]===max).length===1)gains[i]+=category===1&&max===10||category===2&&max===4?2:1;}});teams.forEach((ps,i)=>ps.forEach(p=>s.scores[p]+=gains[i]));const best=Math.max(...gains),win=teams[gains.indexOf(best)][0];finishHand(s,win);if(teams.length===2&&cards.some(cs=>cs.length===0)){finish(s,teams[cards[0].length?0:1][0]);return;}const high=Math.max(...Object.values(s.scores));if(high>=21&&teams.filter(ps=>s.scores[ps[0]]===high).length===1)finish(s,teams.find(ps=>s.scores[ps[0]]===high)![0]);note(s,'Recuento de escobas, cartas, oros y sietes.');}
export const escobaEngine=makeEngine('escoba',(p,seed)=>{const s=base('escoba',p,seed);escobaDeal(s);return s;},(s,p,a)=>{
 requireTurn(s,p);if(s.phase==='result'){check(a.type==='next-hand');s.handNumber++;escobaDeal(s);return;}
 check(a.type==='capture');const c=s.hands[p].find(c=>c.id===a.card);check(c);check(Array.isArray(a.table)&&new Set(a.table).size===a.table.length);const combos=captures15(s.table,15-value(c));if(combos.length)check(combos.some(ids=>ids.length===a.table.length&&ids.every(id=>a.table.includes(id))),'Las cartas deben sumar 15.');else check(a.table.length===0,'No hay captura con esa carta.');take(s,p,c.id);
 s.lastPlay={sequence:(s.lastPlay?.sequence??0)+1,player:p,card:{...c},capturedCount:a.table.length,sweep:false};
 if(a.table.length){const picked=s.table.filter((x:PhysicalCard)=>a.table.includes(x.id));s.table=s.table.filter((x:PhysicalCard)=>!a.table.includes(x.id));s.captured[p].push(c,...picked);s.lastCapture=p;if(!s.table.length){s.sweeps[p]++;s.lastPlay.sweep=true;}}else s.table.push(c);note(s,`${p}: ${a.table.length?'captura':'deja'} ${c.rank} de ${c.suit}.`);next(s,p=>s.hands[p].length>0||s.players.every(id=>!s.hands[id].length));
 if(s.players.every(id=>!s.hands[id].length)){if(s.stock.length)deal(s,Math.min(3,Math.floor(s.stock.length/s.players.length)));else escobaScore(s);}
},(s,p)=>publicView(s,p,{boardKind:'capture',lastPlay:s.lastPlay,table:s.table,sweeps:s.sweeps,selectable:s.players[s.turn]===p&&s.phase==='play',tableSelectable:true,target:21,instruction:'Elige una carta de tu mano y las de la mesa que sumen 15.',options:s.players[s.turn]!==p||s.finished?[]:s.phase==='result'?choices(['Siguiente mano',{type:'next-hand'}]):choices(['Jugar selección',{type:'capture',singleCard:true,tableSelection:true}])}));
