plugins { id 'com.android.application' }
android {
    namespace 'es.elteto.lan'
    compileSdk 35
    defaultConfig { applicationId 'es.elteto.lan'; minSdk 26; targetSdk 35; versionCode 2; versionName '0.1.1' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    sourceSets { main.assets.srcDirs += ['../../../dist'] }
}
dependencies {
    implementation 'org.nanohttpd:nanohttpd-websocket:2.3.1'
    implementation 'com.google.code.gson:gson:2.11.0'
}
